CREATE TABLE EVENTS(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(25) NOT NULL,
    EVENTDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DESCRIPTION TEXT,
    PRIMARY KEY(ID)
) ENGINE=MYISAM COLLATE LATIN1_GENERAL_CS;
